### ISSUE TITLE
Write a pophelp for the 'Description' field

### ISSUE THREAD

**Issue by philwareham** [textpattern/pophelp#10]
Needed for:

* Write page
* Section edit page
* Category edit page

Possibly the same pophelp for all the above, or one each TBC.

**Comment by petecooper** [comment]
It looks like the 3x items in OP are covered as items in https://github.com/textpattern/pophelp/issues/17 - so this can be closed as duplicate.

2nd opinion requested.

**Comment by philwareham** [comment]
Agreed - best keep all the requirements in one issue. Closing.
