### ISSUE TITLE
Missing 4.6 pophelp docs to create

### ISSUE THREAD

**Issue by philwareham** [textpattern/pophelp#17]
- [x] default_publish_status
- [x] publish_date (repurpose existing 'timestamp' doc)
- [x] expire_date (repurpose existing 'timestamp' doc)
- [x] permlink_format
- [x] description (article meta description)
- [x] category_description
- [x] section_description

**Comment by philwareham** [comment]
Need to double check there are no other missing pophelps. I have skimmed through the admin panels myself and not spotted any, but I'd appreciate a second set of eyes on.

**Comment by petecooper** [comment]
I've checked all the areas I can think of, and fixed one flub in https://github.com/textpattern/textpattern/pull/668 (merged already), so consider this a second pair of eyes.

**Comment by philwareham** [comment]
Brillz. I will close this and check it off the 4.6 list. Yay!!
