### ISSUE TITLE
Some pref labels have changed

### ISSUE THREAD

**Issue by philwareham** [textpattern/pophelp#18]
See this commit for reference: https://github.com/textpattern/textpacks/commit/17bcc6e1aa19f18a9400f2dedc3a5567de420b8a

**Comment by petecooper** [comment]
Is this here so the pophelp `h1`s and content tally up properly?

**Comment by philwareham** [comment]
Yep, exactly that reason. Might all be OK now but I haven't checked for a while.

**Comment by petecooper** [comment]
All correct as of this reply timestamp.

The prefs referred to in https://github.com/textpattern/textpacks/commit/17bcc6e1aa19f18a9400f2dedc3a5567de420b8a are all correctly notated, and a cursory check of everything else appears to be OK, too.

This issue can be closed if you're happy, @philwareham.

**Comment by philwareham** [comment]
Cheers!
