### ISSUE TITLE
Make sure the master initially gets help files that are relevant for 4.5.x

### ISSUE THREAD

**Issue by gocom** [textpattern/pophelp#2]
Base initial work on 4.5.x rather than 4.6.0. Once the base is compatible 4.5.x, branch to 4.5-dev, and update the master towards 4.6.0.

This so that we can serve the files from the repository to older Textpattern installations using [textpattern/rpc](https://github.com/textpattern/rpc) server.

**Comment by philwareham** [comment]
Branched off the 4.5 files so we can now add 4.6 files to master.
