### ISSUE TITLE
Tag presentation in pophelp

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#20]
I spotted a few `@@` occurrences when hyperlink code get parsed. Example:

```
You will need to add the "@<txp:comments />@ tag":http://docs.textpattern.io/tags/comments manually in any article-based templates where you want comments to appear.
```

As RPC stuff is served up by Textpattern, the `<txp:comments />` part is smushed down in the article body and `@@` is outputted. Options:

* escape the angle brackets with `&lt;` and `&gt;`
* escape with `notextile`
* change the Textile parse method on the RPC Textpattern
* something else I've overlooked

Also, the hyperlink includes `code`-wrapped text (tag name) as well as plain text (the word 'tags'). It's a lot more straightforward to have one style of text as the hyperlink than mash two together with some Textile and some other bits

What's the preferred format for links to docs pages:

* as-is: `code` text plus plain text
* just the `code` text
* something else I've overlooked

I'm a bit out of the loop on Textpattern of late, so would appreciate advice and/or clarification.

**Comment by petecooper** [comment]
Couple of example grabs attached. One has the tag parsed leaving just the unprocessed `@` and the other doesn't process the `@` or the contained tag.

![safari001](https://cloud.githubusercontent.com/assets/226578/14426533/8babd22c-ffe7-11e5-896b-b421c27ea3a2.png)
![safari002](https://cloud.githubusercontent.com/assets/226578/14426534/8bcdf12c-ffe7-11e5-9242-cd6746f50577.png)

**Comment by petecooper** [comment]
Having thought on this, the most straightforward option would be to escape the brackets with encoding.

Proposal: I'll update one of the pophelps, RPC gets updated for a sanity check, and if all good I'll process the remaining pophelps in the same fashion.

**Comment by philwareham** [comment]
I'm all for straightforward, so that sounds good to me - let me know when that test one is ready and I will put into RPC.

**Comment by philwareham** [comment]
I've tested a few methods and found one that works - please see latest 2 commits

**Comment by petecooper** [comment]
Neat - you beat me to it. Looks workable. So, to clarify:

* links to external sites (wiki, docs on .io, etc) should be `target=_blank`
* any links to other pophelp (if any) - should they keep the same window?
* do you want `rel=` on any links?

**Comment by philwareham** [comment]
Hi,

- Yes
- Yes
- Probably yes! :)

**Comment by petecooper** [comment]
@philwareham I think I've snagged all the duffers and fixed them. Thanks for the RPC attention. Closing for now.
