### ISSUE TITLE
Oxford English i.e. and e.g.

### ISSUE THREAD

**Issue by philwareham** [textpattern/pophelp#23]
Since we are moving to Oxford English as our default version of English language going forward, we need to be consistent with use of i.e. and e.g.

They should not have commas after them, that is an Americanism and should be left to a en-US localisation of the pophelp files if a localisation is desired.

[Reference - i.e.](http://www.oxforddictionaries.com/definition/english/i.e.)
[Reference - e.g.](http://www.oxforddictionaries.com/definition/english/e.g.)

**Comment by petecooper** [comment]
I take responsibility for introducing some of those - thanks for the clarification.

**Comment by philwareham** [comment]
Done.
