### ISSUE TITLE
Missing some languages already live in RPC

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#25]
Background: http://forum.textpattern.com/viewtopic.php?id=46867

`de-de` is mentioned, but it's not in this repo. It makes sense to have it (and other languages not already here) copied into this repo so it can be modified as required.

**Comment by philwareham** [comment]
The pophelp area of RPC is a bit of a mess which is why I only converted the English help into GitHub files. However, attached is an XML export of the whole pophelp database. If you can find a way of separating the files out into useable single files and put into repo then please do. Maybe some converter software can do it.

[pophelp-complete.zip](https://github.com/textpattern/pophelp/files/223405/pophelp-complete.zip)

**Comment by petecooper** [comment]
Cheers, Phil!

**Comment by philwareham** [comment]
Hi Pete,

I've just redone the export with empty results omitted, which reduces the file size somewhat. New file attached.

[pophelp-complete-cleaned.zip](https://github.com/textpattern/pophelp/files/223417/pophelp-complete-cleaned.zip)

**Comment by petecooper** [comment]
OK, I've taken a first pass at converting it to CSV and sorting for some stats. Almost 3,000 entries (including `en-gb` already present in the repo) makes for a considerable repo increase.

I reckon awk could slice the input CSV into separate files easily enough, and I'll happily take dibs, but then there's a whole bag of ongoing translation housekeeping and maintenance hurt at play, and if it's a bit of a mess anyway then I wonder if it's worth postponing this until post-4.6 for now.

**Comment by philwareham** [comment]
We need to pick our battles. There is also the fact that most of the English pophelps, on which these translations were initially based years ago, have been completely updated and rewritten within the last two years whilst none of the others have. Therefore most of the translations are redundant. I was hoping people would write new helps from scratch from my English files (and a Czech person kindly did) but I didn't really do a big push for this to happen.

If, say, the most common languages were on there (de, fr, es) for now, from this dump, then I could live with that. Anything else waits for 4.7 when we will have these as text files bundled with the installation anyway. What do you think?

**Comment by philwareham** [comment]
PS. The reason I've picked those languages is that I know we have active users in those languages who probably would be prompt in updating them in the repo - it's no preference of one language over another.

**Comment by petecooper** [comment]
100% agree. Closing for now.

**Comment by philwareham** [comment]
OK. Can you get those French, German, Spanish files extracted easily?

**Comment by petecooper** [comment]
Yep. Assigned to me for now.

**Comment by philwareham** [comment]
German dump attached, as both CSV and XML, whichever is easiest to handle:

[de.zip](https://github.com/textpattern/pophelp/files/224079/de.zip)

**Comment by philwareham** [comment]
French dump attached, as above:

[fr.zip](https://github.com/textpattern/pophelp/files/224084/fr.zip)

**Comment by philwareham** [comment]
Spanish dump attached, as above:

[es.zip](https://github.com/textpattern/pophelp/files/224090/es.zip)

**Comment by philwareham** [comment]
If any others are need, let me know.
