### ISSUE TITLE
Fix translations

### ISSUE THREAD

**Issue by NicolasGraph** [textpattern/pophelp#28]
As mentioned [here](https://github.com/textpattern/textpattern/issues/727), pop helps need translations fixes.

**Comment by philwareham** [comment]
@petecooper I seem to remember a handful of months back you, or someone else, extracted the various languages' pophelp files from the SQL database - is that correct?

If so, we need to get them into this repo as a starting point for translation fixes.

**Comment by petecooper** [comment]
I have a vague memory of that, too. I'll investigate now.

**Comment by petecooper** [comment]
Yep - found it - https://github.com/textpattern/pophelp/issues/25

I don't recall committing any changes as a result of this, so it raises the question: is it worth re-exporting so it's up-to-date, or shall I just crack on with what's attached in the linked issue?

**Comment by philwareham** [comment]
Great! As the RPC is effectively locked to everyone except me, there would not be any recent updates to various languages (except EN which is already in this repo) - so please commit what you already have. Cheers Pete.

**Comment by philwareham** [comment]
This will become more crucial in Textpattern 4.7 too as we want to bundle the help files in the actual release instead of on an RPC server (same goes for Textpacks too).

**Comment by petecooper** [comment]
These are now being channelled via CrowdIn, and database dumps have been removed, so I'm closing this.

**Comment by philwareham** [comment]
Sorry, should have mentioned this earlier. Yes the English help is now so far from other translations it is better to start any translations afresh. Hence why the deletions.
