### ISSUE TITLE
Bogus `acronym.textile` references?

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#29]
In each of the (currently) 3 database dumps for widely-used languages, there's a reference to the `acronym` pophelp, presumably as part of the Textile callout:

```
<row>
<field name="varname">acronym</field>
<field name="area">textile</field>
<field name="lang">de-de</field>
<field name="title">Abkürzungen</field>
<field name="data_raw">HTML(HyperText Markup Language) erlaubt es, über das Tag @&lt;acronym&gt;@ eine Abkürzung einzugeben. Sie erscheint als Tool-Tip, wenn der Leser mit der Maus über die Abkürzung fährt.

Um eine Abkürzung mit Textile zu definieren, muss der ausgeschriebene Begriff in (Klammern) direkt hinter die Abkürzung geschrieben werden.

*Beispiel*

@ACLU(American Civil Liberties Union)@

Wird zu

@&lt;acronym title=&quot;American Civil Liberties Union&quot;&gt;ACLU&lt;/acronym&gt;@

Die Darstellung im Browser sieht wie folgt aus (bitte mit der Maus über den Text fahren):

bq. ACLU(American Civil Liberties Union)

Hinweis: Textile umschließt automatisch drei oder mehr Großbuchstaben, z. B. USA mit dem &lt;acronym&gt; Tag, auch wenn es keinen Begriff enthält.

&quot;Weitere Informationen(more information on this tag at diveintoaccessibility.org)&quot;:http://diveintoaccessibility.org/day_17_defining_acronyms.html</field>
</row>
```

Thing is, I can't find any reference to it in either the Textpattern core code, or in the English pophelp.

Options:

* make the `acronym.textile` files for the three languages
* forget it ever happened and don't make the `acronym.textile` files for the three languages
* something else

What do?

**Comment by Bloke** [comment]
Presumably these should instead be `abbr.textile` given that `<acronym>` has been dropped from the HTML 5 spec? Is there an abbr file lurking anywhere?

**Comment by petecooper** [comment]
`textfilter/textile/abbreviation.textile` - good spot. OK to transcribe to that instead, then?

**Comment by philwareham** [comment]
Hmmm, I think there should an acronym.textile file too for backwards compatibility (since that HTML tag was changed at Textpattern 4.5's version of Textile, I think).

**Comment by petecooper** [comment]
So, transcribe `acronym` to `textfilter/textile/abbreviation.textile` and `textfilter/textile/acronym.textile` - better?

**Comment by philwareham** [comment]
Yes please!
