### ISSUE TITLE
`bulleted` or `list-bulleted`

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#30]
4.5.7 Write panel callout refers/links to `bulleted`, 4.6.0-beta.2 also refers to `bulleted`.

Filename in refers to `list-bulleted` instead of `bulleted`. OK to rename, @philwareham?

**Comment by philwareham** [comment]
I've changed that intentionally for when we break away from RPC, as it describes doc better (I manually paste these changes into RPC anyway).

**Comment by petecooper** [comment]
(y)
