### ISSUE TITLE
RPC mismatch: `link_category`

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#33]
It looks like one of the RPC pophelps is out of date after the HTML conversion:
![screen shot 2016-12-11 at 21 04 24](https://cloud.githubusercontent.com/assets/226578/21083319/baf3562c-bfe5-11e6-879a-5692665ea898.png)

Note code block at the end, it includes the `@` wrapper from Textile. The file in the repo appears to be up-to-date, so a copy-paste should fix it.

**Comment by philwareham** [comment]
Fixed in RPC, thanks Pete!
