### ISSUE TITLE
`permlink_mode` needs Nginx info

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#38]
Currently only mentions Apache for clean URLs, which are possible in Nginx via the server block.

**Comment by philwareham** [comment]
Hi @petecooper - Happy New Year! You are probably better placed than I to write NGINX info since I have not really used that server (apart from some basic testing in MAMP). Can you do this for us? Cheers!

**Comment by petecooper** [comment]
Happy to, yes. This was really a marker for me anyway, so I'll gladly take dibs.

**Comment by philwareham** [comment]
Bump? ;)

**Comment by petecooper** [comment]
I'll do this today.

**Comment by petecooper** [comment]
Done.
