### ISSUE TITLE
Theme import/export/delete actions - new pophelps needed

### ISSUE THREAD

**Issue by philwareham** [textpattern/pophelp#44]
The current `skin_synchronize` pophelp needs to be split into 3 distinct pophelps:

```
skin_delete_from_database
skin_delete_from_disk
skin_delete_entirely
```

**Comment by petecooper** [comment]
Unless I'm missing something, this was done by @Bloke in https://github.com/textpattern/pophelp/commit/599571da6ef03b89ff2a719c4daa965feb0265e8#diff-d2bb6e4fb80e9e2f5b176f431c42a640 :

* `skin_delete_from_database` is currently at https://github.com/textpattern/pophelp/blob/master/help/en_pophelp.xml#L951
* `skin_delete_from_disk` is currently at https://github.com/textpattern/pophelp/blob/master/help/en_pophelp.xml#L956
* `skin_delete_entirely` is currently at https://github.com/textpattern/pophelp/blob/master/help/en_pophelp.xml#L947

So, closing!
