### ISSUE TITLE
IP address references

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#46]
IP recording has been removed from hits and comments, and we still have some IP address references in pophelp.

Blocker for 4.7.0?

**Comment by philwareham** [comment]
Ideally those need to be amended before 4.7.0 release - can you deal? :)

**Comment by petecooper** [comment]
Yep - assign to me, I'll fix.

See also https://github.com/textpattern/textpattern/issues/1278

**Comment by petecooper** [comment]
Alright, I think that's it. Resolved in https://github.com/textpattern/pophelp/commit/f734d2558d92f929b4b903fa3af0385f94089481 https://github.com/textpattern/pophelp/commit/b2597392ddfc0b1a7f9ed9c9290f5d37da293fae https://github.com/textpattern/pophelp/commit/16e595a588cf37e7155d3dd5b2d22407988b2f81
