### ISSUE TITLE
New Textpattern 4.7.2 pophelps needed

### ISSUE THREAD

**Issue by philwareham** [textpattern/pophelp#47]
- [x] 'Enable development theme preview?' Yes/No pref. `enable_dev_preview`
- [x] 'Advanced options' On/Off pref. `advanced_options`
- [x] 'Custom form template types' pref field. `custom_form_types`
- [x] 'PHP functions enabled in txp:evaluate' pref field. `txp_evaluate_functions`

**Comment by bloatware** [comment]
One more block to add: `txp_evaluate_functions`. This is a comma-separated list of `function` or `alias=function` items, e.g. `md5, replace=str_replace`. The items of this list can be used in `query` attribute of `<txp:evaluate />`:
```
<txp:evaluate query="replace('cats', 'dogs', 'I like cats.')" />
```
`function` should return a scalar value (not array/object).

**Comment by philwareham** [comment]
@bloatware @Bloke @petecooper Hi! Anyone care to provide some text for the two missing pophelps listed above? That would complete the `en` help files for Textpattern 4.7.2.

**Comment by petecooper** [comment]
@philwareham Without knowing what the code does, I'm at a loss to suggest better versions than those outlined in the OP, honestly. They seem sane enough to me based on what (little) I know.

**Comment by philwareham** [comment]
Thanks @bloatware - just need some guidance on the `custom_form_types` pop help and we are finished with these for 4.7.2 release. Can you provide a quick summary and I can fill it out?

**Comment by philwareham** [comment]
All done thanks - closing this one.
