### ISSUE TITLE
Textpattern RPC server reference in pophelp

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#48]
A reference to the Textpattern RPC server are still present:

https://github.com/textpattern/pophelp/blob/master/help/en_pophelp.xml#L379

Bearing in mind a) RPC is legacy as of 4.7.0 and b) pre-4.7.0 clients won't see any update because the Textpattern RPC server isn't updated, is it safe to remove this line?

If safe, I'm a bit hazy on best route to take - defer to @philwareham on CrowdIn as master copy, or do it here?

**Comment by philwareham** [comment]
Hi Pete,

Please update the en_pophep and en-gb_pophelp here and I will then load that master file into Crowdin for future reference.

Cheers!

**Comment by petecooper** [comment]
I've done a pass on all languages, was pretty straightforward since it's a line deletion.

**Comment by philwareham** [comment]
Great, thanks Pete - I'll load the master file into Crowdin before I head off tonight.

**Comment by philwareham** [comment]
Crowdin synced now,
