### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by wion** [textpattern/pophelp#50]
As noted in docs issue 130...
https://github.com/textpattern/textpattern.github.io/issues/130

The pophelp on the Themes panel is massive.

I think the new Themes doc (nearing completion but needing some revisions yet) makes the giant pophelp obsolete...
https://docs.textpattern.com/build/themes-creating-using-and-sharing

Maybe someone wants to rethink that one and tailor it down to a sensible few sentences.

**Comment by wion** [comment]
Oh, sorry. Maybe that was already done.

**Comment by wion** [comment]
Correction it's there. I was looking at Phil's styles site. heh.

So, issues stands.

**Comment by philwareham** [comment]
Fixed via https://github.com/textpattern/pophelp/commit/e3206eda7fc491f0d2e585b626fcc061e10e78ea
