### ISSUE TITLE
NTS: investigate automatic conversion from XML to HTML via XSLT

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#51]
Thoughts on decoupling `pophelp` from `rpc.textpattern.com` to reduce manual work and keep `pophelp` fresh:

* auto fetch latest `pophelp` files from https://github.com/textpattern/pophelp/, then…
* use `xsltproc` to split single XML into HTML files, either on hosted server or GitHub CI, then…
* use static site generator at `pophelp.textpattern.com` or similar to host files, with appropriate web server redirects from `rpc.textpattern.com`.

@philwareham - I can't assign this to me, please add me to whichever team is attached to this repo - no urgency. Thank you.

**Comment by philwareham** [comment]
So this is to remove the legacy RPC usage, yes? i.e. just serve those as flat files now for older Textpattern installs?

**Comment by petecooper** [comment]
Correct. We can do it all with a modern web server and put `rpc` out to pasture.
