### ISSUE TITLE
Requesting commit access please

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#54]
I've got a few amends to make, please may I have commit access?

Happy to do the fork + PR dance but commit access is preferred.

Thank you.

**Comment by philwareham** [comment]
You should have commit rights now.

**Comment by petecooper** [comment]
Thanks @philwareham - getting a 403, can you double check please? Checked in browser and I can't edit files inline (e.g. `README.md`).

![Screenshot 2020-07-28 at 13 40 42](https://user-images.githubusercontent.com/226578/88666440-faa6c180-d0d7-11ea-9e1f-31e55a141cac.png)

**Comment by petecooper** [comment]
Actually:

>Please note that we do not accept pull requests directly to this GitHub repository

It's a bunch of URL changes, do you want that done on CrowdIn?

**Comment by philwareham** [comment]
Ah, my bad - should be fixed now.

**Comment by philwareham** [comment]
> Please note that we do not accept pull requests directly to this GitHub repository

Please do it here just to get 4.8.2 out the door, I'll sync the changes back to Crowdin manually after that.

**Comment by petecooper** [comment]
Done - thanks @philwareham.

I'll update https://github.com/textpattern/textpattern/issues/1513 to include latest pophelps.
