### ISSUE TITLE
Differences in `rel="external"` handling in some pophelps

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#59]
There's some discrepancy with how external links are handled in some pophelp entries. For example, `allow_page_php_scripting` has external link indicators:

![Screenshot 2021-03-08 at 10 14 54](https://user-images.githubusercontent.com/226578/110307918-63073b00-7ff7-11eb-9a12-d9095570da1f.png)

https://github.com/textpattern/pophelp/blob/6f5bac48d3f7eed33cbb670d7a87426db203b33b/help/en_pophelp.xml#L548

…but `admin_side_plugins` doesn't:

![Screenshot 2021-03-08 at 10 14 43](https://user-images.githubusercontent.com/226578/110308149-aeb9e480-7ff7-11eb-9d29-82b10a571a2b.png)

https://github.com/textpattern/pophelp/blob/6f5bac48d3f7eed33cbb670d7a87426db203b33b/help/en_pophelp.xml#L526

Both pophelps are external links, both appear to use `rel="external" target="_blank"`. I'm not sure what it is that's at play here, any ideas?

**Comment by philwareham** [comment]
Will investigate.
